#!/usr/bin/env python3
"""Anatomical LOCATION of the residual cyst false positives vs size-matched true cysts
(main text): for the 26 FP / 26 TP components in fp_component_list.csv, compute — relative to the
GT kidney organ (kidney union tumour union cyst) —
  - depth_med_mm  : median distance of the component's voxels to the organ surface
  - exophytic_frac: fraction of component voxels OUTSIDE the organ
  - touch_tumour  : does the component abut annotated tumour (Type-X neighbourhood)?
  - dist_tumour_mm: distance from component centroid to nearest tumour voxel
  - pole_z        : normalised centroid position along the organ's z-extent
then FP-vs-TP Mann-Whitney on depth & exophytic fraction. Reproduces the reported result:
median subcapsular depth 4.1 vs 4.5 mm (p=0.72), exophytic fraction 0.00 vs 0.00 (p=0.22),
2/26 FP abut tumour, median distance to nearest tumour 89 mm.

Provenance / reproducibility: this reads the per-fold predictions and KiTS23 GT under a working
root (not redistributable — the KiTS23 imaging/segmentations are obtained from the official
challenge, and the per-fold predictions are regenerated by pipeline/rerun_pipeline.sh). The
released, directly-usable artifact is results/fp_location_analysis.json (identical output)."""
import os, csv, json
import numpy as np, SimpleITK as sitk, scipy.ndimage as ndi
from scipy.stats import mannwhitneyu

HERE=os.path.dirname(os.path.abspath(__file__))
ROOT=os.environ.get("KITS23_ROOT", os.path.expanduser("~/KiTS23"))   # raw pred/gt working root (not public)
LIST=os.path.join(HERE,"fp_component_list.csv")
CONN=np.ones((3,3,3),int)

def load(cid,kind):
    p={"gt":f"kits23/dataset/case_{cid}/segmentation.nii.gz",
       "pred":f"holdout_pipeline/soft_majority_rule3_typex/KiTS23_{cid}.nii.gz"}[kind]
    im=sitk.ReadImage(os.path.join(ROOT,p))
    return sitk.GetArrayFromImage(im), np.array(im.GetSpacing()[::-1],float)  # (z,y,x) spacing

def pick_mask(mask, target_vox, overlap=None):
    lab,n=ndi.label(mask,CONN)
    if n==0: return None
    labs=list(range(1,n+1)); sizes=ndi.sum(np.ones_like(lab),lab,labs); cand=labs
    if overlap is not None:
        ov=ndi.sum(overlap.astype(np.uint8),lab,labs); cand=[l for l in labs if ov[l-1]>0]
        if not cand: return None
    best=min(cand,key=lambda l:abs(sizes[l-1]-target_vox))
    return lab==best

def bbox(m,pad=4):
    idx=np.where(m); return tuple(slice(max(0,i.min()-pad),i.max()+pad+1) for i in idx)

rows=list(csv.DictReader(open(LIST)))
res={"FP":[], "TP":[]}
for r in rows:
    arm=r["arm"]
    if arm not in ("FP","TP"): continue                    # skip Type-X reader-study items
    cid=r["case"].zfill(5); tv=float(r["target_vox"])
    pred,sp=load(cid,"pred"); gt,_=load(cid,"gt")
    comp = pick_mask(pred==3, tv) if arm=="FP" else pick_mask(pred==3, tv, overlap=(gt==3))
    if comp is None: continue
    organ=(gt>=1); tum=(gt==2)
    sl=bbox(organ | comp)
    oc, cc, tc = organ[sl], comp[sl], tum[sl]
    edt=ndi.distance_transform_edt(oc, sampling=sp)          # depth inside organ (0 outside)
    depth=edt[cc]
    exo=float((~oc & cc).sum())/float(cc.sum())
    touch=bool((ndi.binary_dilation(cc,iterations=1) & tc).any())
    if tc.any():
        dt=ndi.distance_transform_edt(~tc, sampling=sp)
        ctr=tuple(int(round(x)) for x in ndi.center_of_mass(cc))
        dist_tum=float(dt[ctr])
    else:
        dist_tum=float("inf")
    zc=ndi.center_of_mass(comp)[0]; zs=np.where(organ.any(axis=(1,2)))[0]
    pole=float((zc-zs.min())/(zs.max()-zs.min()+1e-6)) if len(zs)>1 else 0.5
    res[arm].append(dict(case=cid, vox=int(comp.sum()),
        depth_med_mm=round(float(np.median(depth)),2), depth_max_mm=round(float(depth.max()),2),
        exophytic_frac=round(exo,3), touch_tumour=touch,
        dist_tumour_mm=(round(dist_tum,1) if np.isfinite(dist_tum) else None), pole_z=round(pole,3)))

def summ(a,k):
    v=[x[k] for x in a]; return f"median {np.median(v):.2f}  IQR[{np.percentile(v,25):.2f}, {np.percentile(v,75):.2f}]"
for arm in ["FP","TP"]:
    a=res[arm]; print(f"\n=== {arm} (n={len(a)}) ===")
    for k in ["vox","depth_med_mm","exophytic_frac","pole_z"]:
        print(f"  {k:16s}: {summ(a,k)}")
    print(f"  touches tumour   : {sum(x['touch_tumour'] for x in a)}/{len(a)}")
    fin=[x for x in a if x['dist_tumour_mm'] is not None]
    if fin: print(f"  dist_tumour_mm   : {summ(fin,'dist_tumour_mm')}  (n_with_tumour={len(fin)})")
print("\n=== FP vs TP (Mann-Whitney, two-sided) ===")
for k in ["depth_med_mm","exophytic_frac","vox"]:
    fp=[x[k] for x in res['FP']]; tp=[x[k] for x in res['TP']]
    u,p=mannwhitneyu(fp,tp,alternative="two-sided")
    print(f"  {k:16s}: p={p:.3f}  ({'indistinguishable' if p>=0.05 else 'DIFFERS'})")
json.dump(res, open(os.path.join(HERE,"fp_location_analysis.json"),"w"), indent=1)
print("\nsaved fp_location_analysis.json  (released copy: results/fp_location_analysis.json)")
